spring:
  application:
    name: dashlines-news-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://dashlines-eureka-cluster.herokuapp.com/eureka}
  instance:
    preferIpAddress: true